
-- TABLA CATEGORIA TIPO
CREATE TABLE "TIPO_CATEGORIA"
(
"ID" NUMBER(*,0),
"COD_CATEGORIA" VARCHAR2(15) NOT NULL, 
"NOMBRE" VARCHAR2(100) NOT NULL, 
"HABILITADO" NUMBER(1,0)
);
ALTER TABLE "TIPO_CATEGORIA" ADD CONSTRAINT "TIPO_CATEGORIA_PK" PRIMARY KEY ("COD_CATEGORIA");


-- SECUENCIA PARA AUTO INCREMENTAL
CREATE SEQUENCE  "TIPO_CATEGORIA_SEQUENCE"
MINVALUE 1 
INCREMENT BY 1 ;

-- TRIGGER PARA AUTO INCREMENTAL
CREATE OR replace TRIGGER tipo_categoria_on_insert
  BEFORE INSERT ON TIPO_CATEGORIA
  FOR EACH ROW
BEGIN
  SELECT TIPO_CATEGORIA_SEQUENCE.nextval
  INTO :new.id
  FROM dual;
END;

-- TABLA TIPO
CREATE TABLE "TIPO"
(
"ID" NUMBER(*,0),
"COD_TIPO" VARCHAR2(15) NOT NULL, 
"NOMBRE" VARCHAR2(100) NOT NULL, 
"ID_CATEGORIA" NUMBER(3) NOT NULL, 
"HABILITADO" NUMBER(1,0)
);
ALTER TABLE "TIPO" ADD CONSTRAINT "TIPO_PK" PRIMARY KEY ("COD_TIPO");


-- SECUENCIA PARA AUTO INCREMENTAL
CREATE SEQUENCE  "TIPO_SEQUENCE"
MINVALUE 1 
INCREMENT BY 1 ;

-- TRIGGER PARA AUTO INCREMENTAL
CREATE OR replace TRIGGER tipo_on_insert
  BEFORE INSERT ON tipo
  FOR EACH ROW
BEGIN
  SELECT tipo_sequence.nextval
  INTO :new.id
  FROM dual;
END;